### ISSUE TITLE
add a "add a bookmark" to the menu

### ISSUE THREAD

**Issue by dandrake** [kickingvegas/casual-bookmarks#11]
It would be nice if the menu had an option to add a bookmark. It seems weird that you can do all this other stuff with your bookmarks, but you can't add one.

I tried putting this into the Operations section:

        ("+" "Add/set" bookmark-set :transient nil)

The only problem is that `bookmark-set` assumes you're *in* the buffer/file that you want to bookmark. So you'd need to add something that prompts for a buffer or file.

I'll see if I can whip this up, but I did want to document it as a small but nice enhancement.

**Comment by kickingvegas** [comment]
Closing.
